from datetime import datetime


_RISK_MAP = {
    "OBSERVATION": "LOW",
    "SUSPICIOUS":  "MEDIUM",
    "WARNING":     "HIGH",
    "VIOLATION":   "CRITICAL"
}


class EvidenceManager:
    """In-memory store for structured evidence generated by DecisionEngine."""

    def __init__(self):
        self._evidence = []
        self._counter  = 0

    def add_evidence(self, event_type, description, duration, state,
                     metadata=None, screenshot=None):
        self._counter += 1
        entry = {
            "id":              self._counter,
            "timestamp":       datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "event_type":      event_type,
            "description":     description,
            "duration":        duration,
            "behaviour_state": state,
            "risk_level":      _RISK_MAP.get(state, "LOW"),
            "metadata":        metadata or {},
            "screenshot":      screenshot
        }
        self._evidence.append(entry)
        return entry

    def get_all(self) -> list:
        return list(self._evidence)

    def get_summary(self) -> dict:
        by_type, by_risk = {}, {"LOW": 0, "MEDIUM": 0, "HIGH": 0, "CRITICAL": 0}
        for e in self._evidence:
            by_type[e["event_type"]]  = by_type.get(e["event_type"], 0) + 1
            by_risk[e["risk_level"]]  = by_risk.get(e["risk_level"], 0) + 1
        return {"total_events": len(self._evidence), "by_type": by_type, "by_risk": by_risk}

    def get_total(self) -> int:
        return len(self._evidence)
